### ISSUE TITLE
00-fetch_data.py: library.config not found

### ISSUE THREAD

**Issue by wmvanvliet** [neuropycon/neuropycon_demo#1]
in `00-fetch_data.py`:

```python
from library.config import study_path, subjects_dir, meg_dir
```

this file does not exist. Should we import from `params.py` instead?

**Comment by davidmeunier79** [comment]
Indeed, there seems to be an issue with a missing file library.config. @annapasca , can you pls have a look?

**Comment by annapasca** [comment]
sure, I'll take a look now!

**Comment by annapasca** [comment]
> in `00-fetch_data.py`:
> 
> ```python
> from library.config import study_path, subjects_dir, meg_dir
> ```
> 
> this file does not exist. Should we import from `params.py` instead?

Thanks to note it. Now all is imported from `params.py`
